# Generated by Django 4.2 on 2023-05-29 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import misc.utils
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '__first__'),
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField(verbose_name='Register No')),
                ('parent_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Parent/Guardian Phone')),
                ('dob', models.DateField(auto_now_add=True, verbose_name='Date of Birth')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Enrollment Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to=misc.utils.UploadPath.image, verbose_name='Profile Image')),
                ('emergency_contact1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Emergency Contact 1')),
                ('emergency_contact2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Emergency Contact 2')),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Parent Email')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.classroom', verbose_name='Class')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='parents.parent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('student_permission', 'Can perform actions as a Student')],
            },
        ),
    ]
