# Generated by Django 4.2 on 2023-05-27 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount in Naira')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_info', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('ref', models.CharField(blank=True, max_length=50, verbose_name='Reference')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parent', verbose_name='payment')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
