# Generated by Django 4.2 on 2023-05-29 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import misc.utils
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to=misc.utils.UploadPath.image, verbose_name='Profile Photo')),
                ('facebook_profile', models.URLField(blank=True, null=True, verbose_name='Facebook Profile Link')),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Handle')),
                ('twitter_profile', models.URLField(blank=True, null=True, verbose_name='Twitter Profile Link')),
                ('emergency_contact1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact 1')),
                ('emergency_contact2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact 2')),
                ('qualification', models.CharField(max_length=50, verbose_name='Best Qualification')),
                ('resume', models.FileField(upload_to=misc.utils.UploadPath.file_upload_path, verbose_name='Resume')),
                ('salary', models.PositiveIntegerField(verbose_name='Salary')),
                ('description', models.TextField(default='Nice me!!!', verbose_name='description')),
                ('date_of_employment', models.DateField(auto_now_add=True, verbose_name='Date of Employment')),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=50)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single')], default='Single', max_length=50)),
                ('teacher_type', models.CharField(choices=[('Reception', 'Reception'), ('Primary_School', 'Primary school'), ('Secondary School', 'Secondary school')], default='Reception', max_length=100)),
                ('subjects', models.ManyToManyField(to='misc.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('teacher_permission', 'Can perform actions as a teacher')],
            },
        ),
    ]
