# Generated by Django 4.2 on 2023-08-03 21:32

from django.db import migrations, models
import misc.utils


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=misc.utils.UploadPath.image, verbose_name='Profile Photo'),
        ),
    ]
