# Generated by Django 4.2 on 2023-05-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('accounts', '0002_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('class_fee', models.ManyToManyField(blank=True, related_name='fee', to='accounts.fee', verbose_name='Fees')),
                ('teacher', models.ManyToManyField(to='teachers.teacher', verbose_name='Class Teachers')),
            ],
        ),
    ]
